image: node

stages:
    - lint

lint:
    stage: lint
    script:
        - |
            npm install eslint \
            eslint-config-react-app \
            eslint-plugin-flowtype \
            eslint-plugin-import \
            eslint-plugin-jsx-a11y \
            eslint-plugin-react-app
        - node_modules/eslint/bin/eslint.js .

